config/routes.rb
Rails.application.routes.draw do

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :skills
      resources :users do
        get  'skills' => 'users#skills'
        post 'skills/new' => 'users#add_skill'
        post  'skills/:skill_id/like' => 'users#like'
        get  'skills/:skill_id/liking_users' => 'users#liking_users'
      end
    end
  end

  get 'users'        => 'users#index'
  get 'users/:id'    => 'users#show'
  post 'users/login' => 'users#login'
  get 'skills'       => 'skills#index'
  get 'skills/:id'   => 'skills#show'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user_skill
  belongs_to :user

  validates :user_skill,
    uniqueness: {
      message: "既にlikeしています",
      scope: [:user]
    }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :user_skills
  has_many :users, :through => :user_skills

  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_skills
  has_many :skills, :through => :user_skills
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill

  has_many :likes
  has_many :users, :through => :likes
end

app/controllers/api/v1/skills_controller.rb
module Api
  module V1
    class SkillsController < ApplicationController
      skip_before_filter :verify_authenticity_token
      before_action :set_skill, only: [:show, :edit, :update, :destroy]

      # GET /skills
      # GET /skills.json
      def index
        @skills = Skill.all
        render json: @skills
      end

      # GET /skills/1
      # GET /skills/1.json
      def show
        render json: @skill
      end

      # GET /skills/new
      # def new
      #   @skill = Skill.new
      # end

      # GET /skills/1/edit
      # def edit
      # end

      # POST /skills
      # POST /skills.json
      def create
        @skill = Skill.new(skill_params)

        respond_to do |format|
          if @skill.save
            format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
            format.json { render :show, status: :created, location: @skill }
          else
            format.html { render :new }
            format.json { render json: @skill.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /skills/1
      # PATCH/PUT /skills/1.json
      def update
        respond_to do |format|
          if @skill.update(skill_params)
            format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
            format.json { render :show, status: :ok, location: @skill }
          else
            format.html { render :edit }
            format.json { render json: @skill.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /skills/1
      # DELETE /skills/1.json
      def destroy
        @skill.destroy
        respond_to do |format|
          format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_skill
          @skill = Skill.find(params[:id])
        end

      # Never trust parameters from the scary internet, only allow the white list through.
      def skill_params
        params.require(:skill).permit(:name)
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      skip_before_filter :verify_authenticity_token
      before_action :set_user, only: [:show, :edit, :update, :destroy]

      # GET /users
      # GET /users.json
      def index
        @users = User.all
        render 'users/users', formats: 'json', handlers: 'jbuilder'
      end

      # GET /users/1
      # GET /users/1.json
      def show
        render json: @user
      end

      # GET /users/new
      # def new
      #   @user = User.new
      # end

      # GET /users/1/edit
      # def edit
      # end

      # POST /users
      # POST /users.json
      def create
        @user = User.new(user_params)

        if @user.save
          render json: @user
        else
          render json: @user.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /users/1
      # PATCH/PUT /users/1.json
      def update
        if @user.update(user_params)
          render json: @user, status: :ok
        else
          render json: @user.errors, status: :unprocessable_entity
        end
      end

      # DELETE /users/1
      # DELETE /users/1.json
      def destroy
        @user.destroy
        respond_to do |format|
        #   format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      # GET /users/1/skills
      def skills
        @user = User.find(params[:user_id])
        @user_skills = []
        @user.skills.each { |skill|
          @user_skills << UserSkill.find_by(user_id: @user.id, skill_id: skill.id)
        }
        render 'user_skills/user_skills', formats: 'json', handlers: 'jbuilder'
      end

      # POST /users/1/skills/new
      def add_skill
        @user = User.find(params[:user_id])
        @skill = Skill.find_or_create_by(skill_params)
        if !@user.skills.include?(@skill)
          @user.skills << @skill
        end

        if @skill.save
          render json: @skill, status: :created
        else
          render json: @skill.errors, status: :unprocessable_entity
        end
      end

      # POST /users/1/skills/1/like
      def like
        @user_skill = UserSkill.find_by(user_id: params[:user_id], skill_id: params[:skill_id])
        @liking_user_id = params[:user][:user_id]
        @liking_user = User.find(@liking_user_id)
        @like = Like.find_or_create_by(:user_skill_id => @user_skill.id, :user_id => @liking_user.id)

        if @like.save
          render json: @like, status: :created
        else
          render json: @like.errors, status: :unprocessable_entity
        end
      end

      # GET /users/1/skills/1/liking_user
      def liking_users
        @user_skill = UserSkill.find_by(user_id: params[:user_id], skill_id: params[:skill_id])
        @liking_users = @user_skill.users
        render json: @liking_users
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_user
          @user = User.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def user_params
          params.require(:user).permit(:name, :password, {:skill_ids => []})
        end

        def skill_params
          params.require(:skill).permit(:name)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show]

  def index
    @skills = Skill.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
  end

  def login
    @user = User.find_by(user_params)

    if @user
      log_in @user
      head :ok
    else
      flash[:error]  = 'Failed login'
      head :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password, {:skill_ids => []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="App">
<head>
  <title>WantedlyAssignment</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<%= link_to 'Back', skills_path %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="">
      ユーザ一覧
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td>
                <a class="btn btn-primary" href="http://127.0.0.1:3000/users/<%= user.id %>">詳細</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" ng-controller="userCtrl">
  <div class="row">
    <div class="">
      <div class="login_user_name">
        <% if logged_in? %>
        <div class="login_user_name" ng-model="login_user"
        ng-init="login_user={id:'<%= @current_user.id %>', name:'<%= @current_user.name %>'}">
          やぁ、{{login_user.name}}(｀・ω・´)
        </div>
        <% else %>
        <div class="login_user_name" ng-model="login_user"
        ng-init="login_user={id:'0', name:'dummy'}">
          ログインしていません。
          <form novalidate name="loginForm" ng-submit="login()">
            <div>
              ユーザ名:
              <input type="text" name="name" ng-model="name" required>
            </div>
            <div>
              パスワード:
              <input type="text" name="pass" ng-model="pass" required>
            </div>
            <div>
              <input type="submit" value="ログインする" ng-disabled="loginForm.$invalid">
            </div>
          </form>
        </div>
        <% end %>
      </div>

      <br>

      <div class="user_name" ng-model="user"
      ng-init="user={id:'<%= @user.id %>', name:'<%= @user.name %>'}">
        ここは{{user.name}}さんのページだよ(´・ω・｀)
      </div>

      <br>

      <div class="skill_title">
        スキル・特徴
      </div>

      <div class="skill_form">
        <form novalidate name="myForm" ng-submit="addSkill()">
          <input type="text" name="skill" ng-model="skill" required>
          <input type="submit" value="追加" ng-disabled="myForm.$invalid">
        </form>
      </div>

      <br>

      <div class="skills" ng-repeat="skill in skills | orderBy: '-liked'">
        <div class="btn btn-primary" ng-click="likeSkill($index)">
          {{skill.liked}}
        </div>
        <a href="/skills/{{skill.id}}">{{skill.name}}</a>
      </div>

      <br>

      <div class="back_button">
        <a class="btn btn-primary" href="<%= users_path %>">一覧に戻る</a>
      </div>
    </div>
  </div>
</div>